### ISSUE TITLE
Cargo test failed on two cases

### ISSUE THREAD

**Issue by TianlongLiang** [facebookexperimental/hermit#24]
**Describe the bug**
A clear and concise description of what the bug is:

When I run `cargo test` two test case failed. 
```shell
test getrandom_intercepted ... FAILED
test rdrand_rdseed_is_masked ... FAILED

failures:

---- getrandom_intercepted stdout ----
Expecting determinism:
Test Run 1:
thread 'getrandom_intercepted' panicked at 'vdso symbol __vdso_clock_gettime's real size is 5 bytes, but trying to replace it with 8 bytes', /home/tl/.cargo/git/checkouts/reverie-9a587e40a0d7d3be/c448d10/reverie-ptrace/src/vdso.rs:148:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- rdrand_rdseed_is_masked stdout ----
Expecting determinism:
Test Run 1:
thread 'rdrand_rdseed_is_masked' panicked at 'Once instance has previously been poisoned', /home/tl/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:30:16


failures:
    getrandom_intercepted
    rdrand_rdseed_is_masked
```

Indicate any of these common scenarios that apply:

- [ ] a program hangs under hermit
- [x] hermit panics internally
- [ ] hermit runs the program but divergence (nondeterminism) occurs

**To Reproduce**
Minimal input to reproduce the behavior.

`cargo test`

**Expected behavior**

all tests pass

**Environment**

- [x] Linux kernel version (`uname -a`): Linux tl 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- [x] CPU version (`/proce/cpuinfo`): 12th Gen Intel(R) Core(TM) i9-12900KS
- [x] Linux distro flavor (`/etc/issue`, `/etc/redhat-release`): Ubuntu 22.04.1 LTS

**Additional context**
Attach the logs to this issue as a text file generated by `hermit --log=trace --log-file=FOO run`.

I saw people have [similar situation](https://github.com/facebookexperimental/hermit/issues/16#issuecomment-1325709739) that would explain why I failed the first test. But I am not sure what caused the second test to fail. Is it because of some bug in lazy_static?

**Comment by TianlongLiang** [comment]
Thanks to the fix mentioned in [this issue](https://github.com/facebookexperimental/hermit/issues/16#issuecomment-1329963326), the error message I mentioned above is resolved. But a new one emerged: 
```
thread 'rdrand_rdseed_is_masked' panicked at 'Unsupported processor with feature info: FeatureInfo { extended_family_id: 0, extended_model_id: 9, family_id: 6, model_id: 151, stepping_id: 2, brand_index: 0, cflush_cache_line_size: 8, initial_local_apic_id: 4, max_logical_processor_ids: 1, edx_ecx: SSE3 | PCLMULQDQ | SSSE3 | FMA | CMPXCHG16B | PCID | SSE41 | SSE42 | X2APIC | MOVBE | POPCNT | TSC_DEADLINE | AESNI | XSAVE | OSXSAVE | AVX | F16C | RDRAND | HYPERVISOR | FPU | VME | DE | PSE | TSC | MSR | PAE | MCE | CX8 | APIC | SEP | MTRR | PGE | MCA | CMOV | PAT | PSE36 | CLFSH | MMX | FXSR | SSE | SSE2 | SS }
```
Is this because of my CPU?

**Comment by jasonwhite** [comment]
You're assumption is correct; we don't support VMs very well at the moment. In particular, we usually can't intercept the CPUID instruction on VMs. We're working on gracefully continuing if we can't intercept the CPUID instruction, but this will mean that Hermit won't be able to determinize the result of CPUID.

**Comment by TianlongLiang** [comment]
`In particular, we usually can't intercept the CPUID instruction on VMs.` That's my observation too. At first, the error message displayed is "can't intercept the CPUID" or something. For VMware on Windows, I was able to enable the "virtualized CPU performance counter" feature, which would allow the Linux perf tool to run normally, and it actually can intercept the CPUID. But as you can see from the above message, it seems that the CPU feature list is maybe somehow changed or differed from the normal physical machine. So that it couldn't be handled normally, either

**Comment by rrnewton** [comment]
Closing as unsupported/duplicative during the issue cleanup. The follow-up established that this run was under VMware. Hermit depends on CPUID interception and hardware PMU/performance-counter behavior that virtual machines generally do not expose reliably. Bare-metal unsupported-processor failures remain tracked by #40 and #47. If a current VM configuration exposes the required facilities and current main still fails, please open a new issue with the hypervisor settings, CPU details, and complete logs.
