### ISSUE TITLE
DrRacket hangs under hermit

### ISSUE THREAD

**Issue by samth** [facebookexperimental/hermit#26]
**Describe the bug**

Running Drracket (from https://racket-lang.org) hangs Hermit as follows:

[samth@huor:~/tmp/hermit (main) plt] ./target/debug/hermit run ~/sw/plt/racket/bin/drracket
2022-11-28T22:09:38.410475Z  WARN detcore::scheduler: Nondeterministic external actions [DetPid(3)] jumped in the middle of runnable work (1 tasks). Need to record this for reproducibility.
thread 'main' panicked at 'Invariant violation, cannot retrieve handle on guest Stack when there is already a StackGuard still alive.', /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/stack.rs:49:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Indicate any of these common scenarios that apply:

- [x] a program hangs under hermit
- [ ] hermit panics internally
- [ ] hermit runs the program but divergence (nondeterminism) occurs

**To Reproduce**
Minimal input to reproduce the behavior.

Install DrRacket. Run hermit on it.

**Environment**

- [ ] Linux kernel version (`uname -a`): `Linux huor 5.19.0-23-generic #24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- [ ] CPU version (`/proce/cpuinfo`):
- [ ] Linux distro flavor (`/etc/issue`, `/etc/redhat-release`): `Ubuntu 22.10`

**Additional context**

Full backtrace:
<details>
```
/home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/stack.rs:49:13
stack backtrace:
   0:     0x561d09be5230 - std::backtrace_rs::backtrace::libunwind::trace::h10d23c3af93c2280
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x561d09be5230 - std::backtrace_rs::backtrace::trace_unsynchronized::h906cda0856e755be
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x561d09be5230 - std::sys_common::backtrace::_print_fmt::hefc6523cb7ad8c91
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x561d09be5230 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h49a37e386978d813
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x561d09c0c90e - core::fmt::write::h8425617fb2d1025f
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/fmt/mod.rs:1208:17
   5:     0x561d09be0ff5 - std::io::Write::write_fmt::h15ede062d559dc3f
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/io/mod.rs:1682:15
   6:     0x561d09be4ff5 - std::sys_common::backtrace::_print::h2767a5294bfc4f78
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x561d09be4ff5 - std::sys_common::backtrace::print::h64070ee3b66f2452
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x561d09be67bf - std::panicking::default_hook::{{closure}}::h353e8837868bcb61
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/panicking.rs:267:22
   9:     0x561d09be64fa - std::panicking::default_hook::h2b11c396c9cc8a06
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/panicking.rs:286:9
  10:     0x561d09be6ebc - std::panicking::rust_panic_with_hook::h81d7ce2132c30f75
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/panicking.rs:688:13
  11:     0x561d09be6c11 - std::panicking::begin_panic_handler::{{closure}}::h133b7f8abeb2011a
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/panicking.rs:577:13
  12:     0x561d09be56dc - std::sys_common::backtrace::__rust_end_short_backtrace::h3ce415d531cb6e38
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x561d09be6972 - rust_begin_unwind
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/panicking.rs:575:5
  14:     0x561d08795df3 - core::panicking::panic_fmt::h83ecf733a8799bff
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/panicking.rs:65:14
  15:     0x561d08f5887e - reverie_ptrace::stack::GuestStack::new::hf2c590f4769932a3
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/stack.rs:49:13
  16:     0x561d08d9ca30 - <reverie_ptrace::task::TracedTask<L> as reverie::guest::Guest<L>>::stack::{{closure}}::hf2c7543da7057fe2
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/task.rs:2113:15
  17:     0x561d08a9dec8 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he948a4cbc0e5c988
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  18:     0x561d08a12b62 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll{{reify.shim}}::hf27a91fd374016d4
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:86:9
  19:     0x561d08c2ad38 - <core::pin::Pin<P> as core::future::future::Future>::poll::he29622a90d6b2186
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/future.rs:124:9
  20:     0x561d0894eb01 - detcore::syscalls::files::<impl detcore::tool_local::Detcore<T>>::inject_fstat::{{closure}}::he8e47b8a377268aa
                               at /home/samth/tmp/hermit/detcore/src/syscalls/files.rs:69:38
  21:     0x561d08a68e5c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0c0e4f05aac6647c
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  22:     0x561d0897109a - detcore::syscalls::files::<impl detcore::tool_local::Detcore<T>>::add_fd::{{closure}}::hfefa515a8324d8a2
                               at /home/samth/tmp/hermit/detcore/src/syscalls/files.rs:101:46
  23:     0x561d08a8af8d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9b5abe8afaeb4e37
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  24:     0x561d08954a69 - detcore::syscalls::files::<impl detcore::tool_local::Detcore<T>>::handle_socket::{{closure}}::h095eb3d47f8d5d9d
                               at /home/samth/tmp/hermit/detcore/src/syscalls/files.rs:660:13
  25:     0x561d08a8465f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h819e487be3c4b081
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  26:     0x561d08dfacf3 - detcore::<impl reverie::tool::Tool for detcore::tool_local::Detcore<T>>::handle_syscall_event::{{closure}}::h7ecd0201194b6b08
                               at /home/samth/tmp/hermit/detcore/src/lib.rs:941:63
  27:     0x561d08a9bc0f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he0dc5fc101a71f88
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  28:     0x561d08a10b32 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll{{reify.shim}}::h38805c9171dcef19
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:86:9
  29:     0x561d08c2a4e8 - <core::pin::Pin<P> as core::future::future::Future>::poll::ha1be9dfbc23db730
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/future.rs:124:9
  30:     0x561d08d2abfe - reverie_ptrace::task::TracedTask<L>::handle_seccomp::{{closure}}::{{closure}}::h376df5c69e4446b9
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/task.rs:1071:17
  31:     0x561d08a7c2ff - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h602d4a746c39c2c8
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  32:     0x561d0891c042 - <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll::hd68fa42b2d194eeb
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/fuse.rs:86:37
  33:     0x561d08c2a9a6 - <core::pin::Pin<P> as core::future::future::Future>::poll::hcb041347d74d6306
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/future.rs:124:9
  34:     0x561d08c04fd0 - futures_util::future::future::FutureExt::poll_unpin::h2b2f4cb1276ea5f8
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/mod.rs:562:9
  35:     0x561d08d14a28 - reverie_ptrace::task::cancellable::{{closure}}::{{closure}}::{{closure}}::h5f878477426bca09
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/async_await/select_mod.rs:321:13
  36:     0x561d08a337a7 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::ha34ec5228e0cd506
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/ops/function.rs:617:13
  37:     0x561d08d1438f - reverie_ptrace::task::cancellable::{{closure}}::{{closure}}::hc346cc796a4823d1
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/async_await/select_mod.rs:321:13
  38:     0x561d08eecad5 - <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h9b68575c722f460d
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/poll_fn.rs:56:9
  39:     0x561d08d1378c - reverie_ptrace::task::cancellable::{{closure}}::hc49b8f0bfb076cb9
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/task.rs:549:5
  40:     0x561d08a7926f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h53f0e327676659f6
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  41:     0x561d08d27b37 - reverie_ptrace::task::TracedTask<L>::handle_seccomp::{{closure}}::h01b5b155e17096a6
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/task.rs:1073:9
  42:     0x561d08a70cba - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h304f061cc4c17ce7
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  43:     0x561d08d61042 - reverie_ptrace::task::TracedTask<L>::handle_stop_event::{{closure}}::hc805624440b987a8
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/task.rs:872:59
  44:     0x561d08a7bdda - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h5e361b954ff6cd8e
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  45:     0x561d0891bd4e - <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll::hb725db08525ab749
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/fuse.rs:86:37
  46:     0x561d08c2a416 - <core::pin::Pin<P> as core::future::future::Future>::poll::h9b08f6a672bad144
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/future.rs:124:9
  47:     0x561d08c2a846 - <core::pin::Pin<P> as core::future::future::Future>::poll::hb9f491d96859e7cf
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/future.rs:124:9
  48:     0x561d08c051f0 - futures_util::future::future::FutureExt::poll_unpin::h73b744d83665e9ae
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/mod.rs:562:9
  49:     0x561d08d6a6f8 - reverie_ptrace::task::TracedTask<L>::run_loop_internal::{{closure}}::{{closure}}::{{closure}}::hfab170a95abea328
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/async_await/select_mod.rs:331:13
  50:     0x561d08a33747 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h021e893a23705acc
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/ops/function.rs:617:13
  51:     0x561d08d697c5 - reverie_ptrace::task::TracedTask<L>::run_loop_internal::{{closure}}::{{closure}}::h57c90c8fa0a84a3b
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/async_await/select_mod.rs:331:13
  52:     0x561d08eec9e5 - <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h8895812737c05336
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/poll_fn.rs:56:9
  53:     0x561d08d6652a - reverie_ptrace::task::TracedTask<L>::run_loop_internal::{{closure}}::h0d6288d6ffa47595
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/task.rs:1430:34
  54:     0x561d08a724bf - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h377db28668b0c81e
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  55:     0x561d08d89ca4 - reverie_ptrace::task::TracedTask<L>::run_loop::{{closure}}::he799f4aa1b9d3a84
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/task.rs:1374:43
  56:     0x561d08a986af - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd1e0e9444bb8c739
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  57:     0x561d0891b208 - <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll::ha59efcbac3406c93
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/fuse.rs:86:37
  58:     0x561d08c29ad6 - <core::pin::Pin<P> as core::future::future::Future>::poll::h5355162864120d39
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/future.rs:124:9
  59:     0x561d08c2a6b6 - <core::pin::Pin<P> as core::future::future::Future>::poll::hb179adba3acb5390
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/future.rs:124:9
  60:     0x561d08c04e10 - futures_util::future::future::FutureExt::poll_unpin::h0155c64dc97a5b32
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/mod.rs:562:9
  61:     0x561d08d81088 - reverie_ptrace::task::TracedTask<L>::run::{{closure}}::{{closure}}::{{closure}}::h0d232677a889f974
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/async_await/select_mod.rs:331:13
  62:     0x561d08a33777 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h0c741f3122b8e86a
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/ops/function.rs:617:13
  63:     0x561d08d80f3f - reverie_ptrace::task::TracedTask<L>::run::{{closure}}::{{closure}}::ha925df7b5df4800c
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/async_await/select_mod.rs:331:13
  64:     0x561d08eecb25 - <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::hb18ebfb984978949
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/poll_fn.rs:56:9
  65:     0x561d08d80094 - reverie_ptrace::task::TracedTask<L>::run::{{closure}}::h66287908cfdf8084
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/task.rs:1458:13
  66:     0x561d08a7157f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h31c403a5fecfc14c
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  67:     0x561d08d4a1b1 - reverie_ptrace::task::TracedTask<L>::handle_new_task::{{closure}}::{{closure}}::h6ba802189b9c0b91
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/task.rs:1162:40
  68:     0x561d08a92a17 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb9c10e317da1ae4b
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  69:     0x561d08a1d15a - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h1aeca48d8d20758d
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/core.rs:208:17
  70:     0x561d08ec1893 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h5d7c7f51a603e046
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/loom/std/unsafe_cell.rs:14:9
  71:     0x561d08a1cdfe - tokio::runtime::task::core::Core<T,S>::poll::ha7d8cdc40472d719
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/core.rs:197:13
  72:     0x561d08e29768 - tokio::runtime::task::harness::poll_future::{{closure}}::h184600b94b4ab9ce
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:483:19
  73:     0x561d08f0d3c4 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h691d604d245ad685
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/panic/unwind_safe.rs:271:9
  74:     0x561d08f0aa13 - std::panicking::try::do_call::h9ca0843f0bbef174
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/panicking.rs:483:40
  75:     0x561d08f0d04b - __rust_try
  76:     0x561d08f08c75 - std::panicking::try::h9d0b193a1982487c
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/panicking.rs:447:19
  77:     0x561d08f071bb - std::panic::catch_unwind::h20254fcb007495b5
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/panic.rs:137:14
  78:     0x561d08e28454 - tokio::runtime::task::harness::poll_future::h6f9d571c089a95d1
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:471:18
  79:     0x561d08e2a3c9 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h11a4062c2dd29a68
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:107:27
  80:     0x561d08e2de37 - tokio::runtime::task::harness::Harness<T,S>::poll::h4d29fd932fabc549
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:61:15
  81:     0x561d08ebda5d - tokio::runtime::task::raw::poll::h4319ea9e067afe07
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/raw.rs:194:5
  82:     0x561d09640017 - tokio::runtime::task::raw::RawTask::poll::h02abc402f70a34ce
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/raw.rs:134:18
  83:     0x561d09671602 - tokio::runtime::task::LocalNotified<S>::run::hfa2aec41813b7df6
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/mod.rs:430:9
  84:     0x561d0968da2b - tokio::task::local::LocalSet::tick::{{closure}}::h5f62d636078bc7f6
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:616:63
  85:     0x561d0968d95e - tokio::runtime::coop::with_budget::h7b40bd72ef0cd0c8
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
  86:     0x561d0968d95e - tokio::runtime::coop::budget::h2c821f86aaa47d68
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
  87:     0x561d0968d95e - tokio::task::local::LocalSet::tick::h75f004123041ca2e
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:616:31
  88:     0x561d08e25419 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::h40502f127a08f852
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:928:16
  89:     0x561d08e24ede - tokio::task::local::LocalSet::with::{{closure}}::h96c1607f9c348ab8
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:685:13
  90:     0x561d08efc780 - std::thread::local::LocalKey<T>::try_with::heceb90da7710968a
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/thread/local.rs:446:16
  91:     0x561d08ef95b5 - std::thread::local::LocalKey<T>::with::hcfbdc9ef4d2e5a49
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/std/src/thread/local.rs:422:9
  92:     0x561d08e24de7 - tokio::task::local::LocalSet::with::h8ac50832d93ac51d
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:668:9
  93:     0x561d08e252ae - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::hf448140e1273f2b9
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:914:9
  94:     0x561d08e25190 - tokio::task::local::LocalSet::run_until::{{closure}}::h8d0ce48e62f84b4f
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/task/local.rs:574:18
  95:     0x561d08a7eb1f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6bfe0523169051c3
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  96:     0x561d08cf3807 - reverie_ptrace::tracer::Tracer<G>::wait::{{closure}}::h4f5eefc390d1d880
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-ptrace/src/tracer.rs:136:59
  97:     0x561d08a88d6a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h94f5222266f92d72
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
  98:     0x561d08e1c195 - hermit::run::{{closure}}::ha857b12a82679c5d
                               at /home/samth/tmp/hermit/hermit-cli/src/lib.rs:83:68
  99:     0x561d08a6c39e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1c634a8fff7e941e
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/mod.rs:92:19
 100:     0x561d08c298ad - <core::pin::Pin<P> as core::future::future::Future>::poll::h4380eac278bbde52
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/future/future.rs:124:9
 101:     0x561d08cd2605 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}::he24854748a7bd164
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:531:57
 102:     0x561d08cd2194 - tokio::runtime::coop::with_budget::h9fad552364031e0c
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
 103:     0x561d08cd2194 - tokio::runtime::coop::budget::h78018ab8b5e68a4e
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
 104:     0x561d08cd2194 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::hef0af0a12f297990
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:531:25
 105:     0x561d08cc7234 - tokio::runtime::scheduler::current_thread::Context::enter::h33233046e64220c9
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:340:19
 106:     0x561d08ccd07e - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::h4b79cf47016640c1
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:530:36
 107:     0x561d08ccc8a3 - tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}::hd41b8064167235ee
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:601:57
 108:     0x561d08dbaea4 - tokio::macros::scoped_tls::ScopedKey<T>::set::h7ad86506c875e536
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/macros/scoped_tls.rs:61:9
 109:     0x561d08ccb0b5 - tokio::runtime::scheduler::current_thread::CoreGuard::enter::h5ce8233911a56bca
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:601:27
 110:     0x561d08cccae4 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::h3f027abfc0d5c20d
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:520:19
 111:     0x561d08cc4a18 - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::h812a392725c583d9
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:154:24
 112:     0x561d08e1b04b - tokio::runtime::runtime::Runtime::block_on::h5bb6b4488c4c3088
                               at /home/samth/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/runtime.rs:279:47
 113:     0x561d088c2a87 - hermit::run::h576707dce72b2b4b
                               at /home/samth/tmp/hermit/hermit-cli/src/lib.rs:85:5
 114:     0x561d087b037e - hermit::run::RunOpts::run_in_container::h00da008975595fc4
                               at /home/samth/tmp/hermit/hermit-cli/src/bin/hermit/run.rs:933:9
 115:     0x561d088820a0 - hermit::run::RunOpts::run::{{closure}}::hdb47ddb45f1297cf
                               at /home/samth/tmp/hermit/hermit-cli/src/bin/hermit/run.rs:737:43
 116:     0x561d0886212f - hermit::container::with_container::{{closure}}::he6fe7c108d54a719
                               at /home/samth/tmp/hermit/hermit-cli/src/bin/hermit/container.rs:44:17
 117:     0x561d087c81ca - reverie_process::container::Container::run::{{closure}}::{{closure}}::h8c8b8ad03e7d6032
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-process/src/container.rs:794:68
 118:     0x561d087cc9df - core::result::Result<T,E>::map::h5121a42bb86615bb
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/core/src/result.rs:775:25
 119:     0x561d087c804f - reverie_process::container::Container::run::{{closure}}::hf4f31cd842d75239
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-process/src/container.rs:794:29
 120:     0x561d095ace36 - <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::h45130065f054374a
                               at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library/alloc/src/boxed.rs:2016:9
 121:     0x561d095ab1e4 - reverie_process::clone::clone_with_stack::callback::h22426b4f7e63dbba
                               at /home/samth/.cargo/git/checkouts/reverie-8ef5283cec164105/a7f6cae/reverie-process/src/clone.rs:29:9
 122:     0x7f754d91e744 - __GI___clone
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```
</details>

Attach the logs to this issue as a text file generated by `hermit --log=trace --log-file=FOO run`.

**Comment by samth** [comment]
@rrnewton here's the hang we discussed.
